_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 16
                - 55
            "4": 3.9.21
            "5": 0.20.1
            "6": 4.53.2
            "12": 0.20.1
            "13": darwin-arm64
batch_size:
    value: 4
learning_rate:
    value: 5e-05
lora_alpha:
    value: 32
lora_dropout:
    value: 0.1
lora_r:
    value: 16
max_length:
    value: 512
model_name:
    value: Qwen/Qwen1.5-0.5B
num_epochs:
    value: 3
warmup_steps:
    value: 100
